# fly.toml app configuration file generated for artikel-fast on 2025-01-05T20:22:12+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'artikel-fast'
primary_region = 'mad'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8080'
  CORS_ORIGINS="*"
  ENVIRONMENT="PRODUCTION"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
